export default [
  {
    path: '/login',
    layout: false,
    component: './Login',
  },
  {
    path: '/',
    component: './RootRedirect',
  },
  {
    path: '/dashboard',
    name: '总览',
    icon: 'dashboard',
    component: './Dashboard',
    access: 'canViewDashboard',
  },
  {
    key: 'workbench',
    name: '工作台',
    icon: 'checkCircle',
    routes: [
      {
        path: '/tasks',
        name: '我的待办',
        icon: 'checkCircle',
        component: './Tasks',
        access: 'canHandleTask',
      },
      {
        path: '/task-claims',
        name: '待认领',
        icon: 'audit',
        component: './Tasks',
        access: 'canClaimTask',
      },
      {
        path: '/done-tasks',
        name: '已办任务',
        icon: 'fileDone',
        component: './Tasks',
        access: 'canHandleTask',
      },
      {
        path: '/started-instances',
        name: '我发起的',
        icon: 'profile',
        component: './Tasks',
        access: 'canViewOwnWork',
      },
      {
        path: '/tasks/:taskId',
        name: '任务详情',
        hideInMenu: true,
        component: './TaskDetail',
        access: 'canViewOwnWork',
      },
    ],
  },
  {
    key: 'process-center',
    name: '流程中心',
    icon: 'playCircle',
    routes: [
      {
        path: '/process-start',
        name: '发起流程',
        icon: 'playCircle',
        component: './ProcessInstances',
        access: 'canStartProcess',
      },
      {
        path: '/process-instances',
        name: '流程实例',
        icon: 'profile',
        component: './ProcessInstances',
        access: 'canOperateSystem',
      },
      {
        path: '/process-instances/:instanceId',
        name: '实例详情',
        hideInMenu: true,
        component: './ProcessInstanceDetail',
        access: 'canViewProcessContext',
      },
    ],
  },
  {
    key: 'process-modeling',
    name: '流程配置',
    icon: 'partition',
    access: 'canConfigureWorkflow',
    routes: [
      {
        path: '/process-models',
        name: '流程模型',
        icon: 'deploymentUnit',
        component: './ProcessModels',
      },
      {
        path: '/process-designer',
        name: '流程设计',
        icon: 'edit',
        component: './ProcessDesigner',
      },
      {
        path: '/forms',
        name: '表单管理',
        icon: 'form',
        component: './Forms',
      },
      {
        path: '/form-bindings',
        name: '表单绑定',
        icon: 'link',
        component: './FormBindings',
      },
    ],
  },
  {
    key: 'organization',
    name: '组织与系统',
    icon: 'team',
    access: 'canManageOrganization',
    routes: [
      {
        path: '/organization-permissions',
        name: '组织权限',
        icon: 'team',
        component: './SystemSettings',
      },
      {
        path: '/system-settings',
        name: '系统设置',
        icon: 'setting',
        component: './SystemSettings',
        access: 'canManageSystem',
      },
    ],
  },
  {
    key: 'integration',
    name: '集成管理',
    icon: 'api',
    access: 'canManageIntegration',
    routes: [
      {
        path: '/datasources',
        name: '数据源管理',
        icon: 'database',
        component: './DataSources',
      },
      {
        path: '/http-connector',
        name: '集成动作',
        icon: 'cloudSync',
        component: './HttpConnector',
      },
    ],
  },
  {
    key: 'ops',
    name: '运维审计',
    icon: 'control',
    access: 'canViewAudit',
    routes: [
      {
        path: '/ops',
        name: '运维中心',
        icon: 'control',
        access: 'canOperateSystem',
        component: './Ops',
      },
      {
        path: '/audit-logs',
        name: '审计日志',
        icon: 'fileSearch',
        access: 'canViewAudit',
        component: './AuditLogs',
      },
    ],
  },
  {
    component: './exception/404',
    layout: false,
    path: '*',
  },
];
